blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^create/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$', views.BlogDetail.as_view(), name='detail')
]

tuto_experts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.default.views import RegistrationView

from theme import views
from users import forms, views as userViews

admin.site.te_header = "Tuto Experts"
admin.site.site_title = "Administrador Tuto Experts"
admin.site.index_title = "Bienvenido"


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^checkout/', userViews.CheckoutView.as_view(), name='checkout'),
    url(r'^payment_response/', userViews.PaymentResponseView.as_view(), name='payment_response'),
    url(r'^payment_confirmation/', userViews.payment_confirmation, name='payment_confirmation'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.FaqsIndex.as_view(), name='faqs'),
    url(r'^feedback/', userViews.FeedbackIndex.as_view(), name='feedback'),
    url(r'^about-us/', views.AboutUs, name='about'),
    url(r'^subjects/', userViews.SubjectIndex.as_view(), name='subjects'),
    url(r'^terms-and-conditions/', views.TermsAndConditions, name='terms_and_conditions'),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/register/student/', RegistrationView.as_view(form_class=forms.StudentSignUpForm), name='student_signup'),
    url(r'^accounts/register/teacher/', userViews.TeacherRegistrationView.as_view(), name='teacher_signup'),
    url(r'^accounts/social/register/', userViews.social_registration, name='social_register'),
    url(r'^accounts/social/login/', userViews.social_login, name='social_login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^config/', admin.site.urls),
    url(r'^particular-classes/', views.ParticularClasses, name='particular_classes'),
    url(r'^reservation-confirmation/(?P<reservation_code>\w+)/$', userViews.ReservationConfirmationView.as_view(), name='reservation-confirmation'),
    url(r'^reservation-detail/(?P<reservation_code>\w+)/$', userViews.ReservationResumeDetailView.as_view(), name='reservation-detail')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import re
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.template import defaultfilters
from django.db.models.signals import post_save
from redactor.fields import RedactorField
from unidecode import unidecode
from datetime import datetime


from .signals import save_comment


class Category(models.Model):
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True, verbose_name='Activo')

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorías'


class Post(models.Model):

    def attachment_folder(self, filename):
        now = datetime.now()
        return '/'.join(['blog/uploads/', now.strftime('%Y/%m/%d'), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])

    title = models.CharField(max_length=200, verbose_name='Titulo')
    slug = models.SlugField()
    body_text = RedactorField(verbose_name='Texto', upload_to=attachment_folder, redactor_options={'lang': 'es', 'focus': True})
    post_date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')
    modified = models.DateTimeField(null=True, verbose_name='Fecha Modificación')
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, verbose_name='Autor', on_delete=models.SET_NULL)
    allow_comments = models.BooleanField(default=True, verbose_name='Permitir Comentarios')
    comment_count = models.IntegerField(blank=True, default=0, verbose_name='Comentarios')
    featured_image = models.ImageField(upload_to=attachment_folder, blank=True, null=True, verbose_name='Imagen')
    category = models.ForeignKey(Category, null=True, related_name='category', verbose_name='Categoría', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ['-post_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug,
            'year': '%04d' % self.post_date.year,
            'month': '%02d' % self.post_date.month,
            'day': '%02d' % self.post_date.day,
        }

        return reverse('blog:detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        slug = defaultfilters.slugify(self.title[:45])
        same_slug = Post.objects.filter(slug__startswith=slug)

        if same_slug:
            slug = defaultfilters.slugify(self.title[:45] + ' ' + str(same_slug.count()))

        self.slug = slug
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', verbose_name='Post', on_delete=models.CASCADE)
    body_text = models.TextField(verbose_name='Mensaje')
    post_date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    ip_address = models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name='Usuario', related_name='comment_user', on_delete=models.SET_NULL)
    user_name = models.CharField(max_length=50, default='anonymous', verbose_name='Nombre de Usuario')
    user_email = models.EmailField(blank=True, verbose_name='Correo')

    def __str__(self):
        return self.body_text

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentarios'
        ordering = ['-post_date']


post_save.connect(save_comment, sender=Comment)

blog/forms.py
from django import forms
from redactor.widgets import RedactorEditor
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body_text', 'post', 'user']
        widgets = {
            'post': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            'body_text': forms.Textarea(attrs={'class': 'sm-form-control', 'cols': '58', 'rows': '7', 'tabindex': '4'})
        }


class PostAdminForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'allow_comments', 'featured_image', 'body_text')
        widgets = {
            'body_text': RedactorEditor()
        }

blog/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormMixin
from .models import Post, Comment
from .forms import CommentForm

# Create your views here.


class BlogIndex(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 5
    queryset = Post.objects.all()


class BlogDetail(FormMixin, generic.DetailView):
    template_name = 'blog/detail.html'
    model = Post
    form_class = CommentForm

    def get_success_url(self):
        kwargs = {
            'slug': self.object.slug,
            'year': '%04d' % self.object.post_date.year,
            'month': '%02d' % self.object.post_date.month,
            'day': '%02d' % self.object.post_date.day,
        }
        return reverse('blog:detail', kwargs=kwargs)

    def get_context_data(self, **kwargs):
        context = super(BlogDetail, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object, 'user': self.request.user})
        context['related_posts'] = Post.objects.filter(category=self.object.category).exclude(pk=self.object.pk)[0:4]
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(BlogDetail, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class BlogCreate(generic.CreateView):
    template_name = 'blog/create_blog.html'
    model = Post
    fields = ['title', 'body_text', 'allow_comments', 'featured_image', 'category']

    def form_valid(self, form):
        post = form.save()
        post.posted_by = self.request.user
        post.save()
        return redirect('blog:index')

blog/templates/blog/comments.html
{% if post.comments %}

<!-- Comments
	============================================= -->

<!-- Comments List
		============================================= -->
<ol class="commentlist clearfix">

	{% for comment in post.comments.all %}

	<li class="comment even thread-even depth-1" id="li-comment-1">


		<div id="comment-1" class="comment-wrap clearfix">

			<div class="comment-meta">

				<div class="comment-author vcard">

					<span class="comment-avatar clearfix">
						<img alt='' src='http://0.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=60' class='avatar avatar-60 photo avatar-default' height='60' width='60' /></span>

				</div>

			</div>

			<div class="comment-content clearfix">

				<div class="comment-author"> {{ comment.user }}<span>{{ comment.post_date }}</span></div>

				<p>{{ comment.body_text }}</p>

			</div>

			<div class="clear"></div>

		</div>

	</li>
	{% endfor %}

</ol><!-- .commentlist end -->

<div class="clear"></div>
{% endif %}

<!-- Comment Form
============================================= -->
{% if user.is_authenticated %}
<div id="respond" class="clearfix">

	<h3>Deja <span>tu comentario</span></h3>

	<form class="clearfix" action="#" method="post" id="commentform">
		{% csrf_token %}

		<div class="col_full">
			{{ form }}
		</div>

		<div class="col_full nobottommargin">
			<button name="submit" type="submit" id="submit-button" tabindex="5" value="Submit" class="button button-3d button-rounded button-green nomargin">Enviar</button>
		</div>

	</form>

</div><!-- #respond end -->

{% else %}
<h3 id="comments-title"><span>Para comentar debe estar autenticado!</span> </h3>
{% endif %}

blog/templates/blog/create_blog.html
{% extends "base.html" %}
<!-- archivos staticos -->
{% load static i18n humanize mathfilters widget_tweaks %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Nueva Entrada {% endblock title %}
<!-- Contenido -->
{% block content %}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="col_full required">
                    <p class="error-color">{{ form.title.errors }}</p>
                    <label for="{{ form.title.id_for_label }}" class="required">{{ form.title.label }}:</label>
                    {% render_field form.title class+="sm-form-control required" %}
                    <p class="help">{{ form.title.help_text|safe }}</p>
                </div>

                <div class="col_one_third required">
                    <p class="error-color">{{ form.category.errors }}</p>
                    <label for="{{ form.category.id_for_label }}" class="required">{{ form.category.label }}:</label>
                    {% render_field form.category class+="sm-form-control required" %}
                    <p class="help">{{ form.category.help_text|safe }}</p>
                </div>
                <div class="col_one_third required">
                    <p class="error-color">{{ form.featured_image.errors }}</p>
                    <label for="{{ form.featured_image.id_for_label }}" class="required">{{ form.featured_image.label }}:</label>
                    {% render_field form.featured_image class+="sm-form-control required file" accept="image/*" %}
                    <p class="help">{{ form.featured_image.help_text|safe }}</p>
                </div>
                <div class="col_one_third col_last required">
                    <p class="error-color">{{ form.allow_comments.errors }}</p>
                    {% render_field form.allow_comments class+="sm-form-control required checkbox-style" %}
                    <label for="{{ form.allow_comments.id_for_label }}" class="checkbox-style-1-label">{{ form.allow_comments.label }}:</label>
                    <p class="help">{{ form.allow_comments.help_text|safe }}</p>
                </div>

                <div class="col_full required">
                    <p class="error-color">{{ form.body_text.errors }}</p>
                    <label for="{{ form.body_text.id_for_label }}" class="required">{{ form.body_text.label }}:</label>
                    {% render_field form.body_text class+="sm-form-control required" %}
                    <p class="help">{{ form.body_text.help_text|safe }}</p>
                </div>

                <input type="submit" value="{% trans 'Submit' %}" class="button button-3d button-rounded button-green nomargin center" />

            </form>
        </div>
    </div>
</section>
{% endblock %}
<!-- adicional css -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/components/bs-filestyle.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/components/redactor.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/components/radio-checkbox.css' %}" type="text/css" />
{% endblock %}
<!-- adicional js -->
{% block extra_js %}
<script src="{% static 'js/components/bs-filestyle.js' %}"></script>
<script src="{% static 'js/components/redactor.min.js' %}"></script>
<script src="{% static 'redactor/plugins/alignment.min.js' %}"></script>
<script src="{% static 'redactor/plugins/counter.min.js' %}"></script>
<script src="{% static 'redactor/plugins/fontcolor.min.js' %}"></script>
<script src="{% static 'redactor/plugins/fontfamily.min.js' %}"></script>
<script src="{% static 'redactor/plugins/fontsize.min.js' %}"></script>
<script src="{% static 'redactor/plugins/table.min.js' %}"></script>
<script src="{% static 'redactor/plugins/video.min.js' %}"></script>
<script type="text/javascript">
    $(".file").fileinput({
        showUpload: false,
        showPreview: false,
        browseLabel: 'Buscar',
        browseIcon: '<i class="icon-search3"></i>',
        removeLabel: 'Cancelar',
        removeTitle: 'Cancelar archivos seleccionados',
        removeIcon: '<i class="icon-remove"></i>',
        msgPlaceholder: 'Seleccionar archivo'
    })

    $('#id_body_text').redactor({
        plugins: ['alignment', 'counter', 'fontcolor', 'fontfamily', 'fontsize', 'table', 'video']
    })
</script>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% load i18n %}
<!-- title block -->
{% block title %} {{ block.super}} | Blog {% endblock %}

<!-- Content block -->
{% block content %}

<section id="content">

	<div class="content-wrap">

		<div class="container clearfix">

			<div class="single-post nobottommargin">

				<!-- Single Post
						============================================= -->
				<div class="entry clearfix">

					<!-- Entry Title
							============================================= -->
					<div class="entry-title">
						<h2>{{ post.title }}</h2>
					</div><!-- .entry-title end -->

					<!-- Entry Meta
							============================================= -->
					<ul class="entry-meta clearfix">
						<li><i class="icon-calendar3"></i> {{ post.post_date }}</li>
						<li><a href="#"><i class="icon-user"></i> {{ post.posted_by }}</a></li>
						<li><i class="icon-folder-open"></i>{{ post.category }}</li>
						<li><a href="#"><i class="icon-comments"></i> {{ post.comment_count }} </a></li>
					</ul><!-- .entry-meta end -->

					<!-- Entry Image
							============================================= -->
					{% if post.featured_image %}
					<div class="entry-image bottommargin">
						<a href="{{ post.featured_image.url }}"><img src="{{ post.featured_image.url }}" alt="{{post.title}}"></a>
					</div><!-- .entry-image end -->
					{% endif %}
					<!-- Entry Content
							============================================= -->
					<div class="entry-content notopmargin">
						{{ post.body_text | safe }}
						<div class="clear"></div>
					</div>
				</div><!-- .entry end -->


				<div id="comments" class="clearfix">

					<h3 id="comments-title"><span>{{ post.comment_count }}</span> Comentario{{ post.comment_count|pluralize }}</h3>

					{% include 'blog/comments.html' %}
				</div><!-- #comments end -->

				<div class="line"></div>

				{% if related_posts %}

				<h4>Quizás te pueda interesar</h4>

				{% for r_post in related_posts %}

				<div class="col_half {% if not forloop.counter0|divisibleby:2 %} col_last {% endif %} mpost clearfix">

					{% if r_post.featured_image %}
					<div class="entry-image">
						<a href="{{ r_post.get_absolute_url }}" data-lightbox="image">
							<img class="image_fade" src="{{ r_post.featured_image.url }}" alt="{{ r_post.title}}">
						</a>
					</div>
					{% endif %}
					<div class="entry-c">
						<div class="entry-title">
							<h4>
								<a href="{{ r_post.get_absolute_url }}">{{ r_post.title }}</a>
							</h4>
						</div>
						<ul class="entry-meta clearfix">
							<li><i class="icon-calendar3"></i> {{ r_post.post_date }}</li>
							<li><i class="icon-comments"></i> {{ r_post.comment_count }}</li>
						</ul>
						<div class="entry-content">
							<p>{{ r_post.body_text | safe |truncatewords:20 }}</p>
						</div>
					</div>
				</div>

				{% endfor %}

				{% endif %}

			</div>

		</div>

	</div>

</section><!-- #content end -->

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% load i18n %}
<!-- title block -->
{% block title %} {{ block.super}} | Blog {% endblock %}

<!-- Content block -->
{% block content %}

<section id="content">

	<div class="content-wrap">

		<div class="container clearfix">

			{% for post in posts %}
			<div id="posts" class="small-thumbs">

				<div class="entry clearfix">
					{% if post.featured_image %}
					<div class="entry-image">
						<a href="{{ post.featured_image.url }}" data-lightbox="image"><img class="image_fade" src="{{ post.featured_image.url }}" alt="{{ post.title }}"></a>
					</div>
					{% endif %}
					<div class="entry-c">
						<div class="entry-title">
							<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
						</div>
						<ul class="entry-meta clearfix">
							<li><i class="icon-calendar3"></i> {{ post.post_date }}</li>
							<li><a href="#"><i class="icon-user"></i> {{ post.posted_by }}</a></li>
							<li><i class="icon-folder-open"></i> {{ post.category }}</li>
							<li><i class="icon-comments"></i> {{ post.comment_count }}</li>
						</ul>
						<div class="entry-content">
							<p>{{ post.body_text | safe | truncatewords:40 }}</p>
							<a href="{{ post.get_absolute_url }}" class="more-link">Leer Mas...</a>
						</div>
					</div>
				</div>
				{% empty %}
				<div class="heading-block center">
					<h2><i class="fa fa-icon-frown-o fa-icon-4x"></i></h2>
					<span>No existen entradas a la fecha</span>
				</div>
				{% endfor %}

				<!-- Pagination
					============================================= -->
				{% if is_paginated %}
				<div class="row mb-3">
					<div class="col-12">
						{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-dark float-left">&larr; Anteriores</a>
						{% endif %}
						{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-secondary float-right">Recientes &rarr;</a>
						{% endif %}
					</div>
				</div>
				{% endif %}
				<!-- .pager end -->

			</div>

		</div>

</section>
{% endblock %}