blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^create/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$', views.BlogDetail.as_view(), name='detail')
]

tuto_experts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.default.views import RegistrationView

from theme import views
from users import forms, views as userViews

admin.site.te_header = "Tuto Experts"
admin.site.site_title = "Administrador Tuto Experts"
admin.site.index_title = "Bienvenido"


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^checkout/', userViews.CheckoutView.as_view(), name='checkout'),
    url(r'^payment_response/', userViews.PaymentResponseView.as_view(), name='payment_response'),
    url(r'^payment_confirmation/', userViews.payment_confirmation, name='payment_confirmation'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.FaqsIndex.as_view(), name='faqs'),
    url(r'^feedback/', userViews.FeedbackIndex.as_view(), name='feedback'),
    url(r'^about-us/', views.AboutUs, name='about'),
    url(r'^subjects/', userViews.SubjectIndex.as_view(), name='subjects'),
    url(r'^terms-and-conditions/', views.TermsAndConditions, name='terms_and_conditions'),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/register/student/', RegistrationView.as_view(form_class=forms.StudentSignUpForm), name='student_signup'),
    url(r'^accounts/register/teacher/', userViews.TeacherRegistrationView.as_view(), name='teacher_signup'),
    url(r'^accounts/social/register/', userViews.social_registration, name='social_register'),
    url(r'^accounts/social/login/', userViews.social_login, name='social_login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^config/', admin.site.urls),
    url(r'^particular-classes/', views.ParticularClasses, name='particular_classes'),
    url(r'^reservation-confirmation/(?P<reservation_code>\w+)/$', userViews.ReservationConfirmationView.as_view(), name='reservation-confirmation'),
    url(r'^reservation-detail/(?P<reservation_code>\w+)/$', userViews.ReservationResumeDetailView.as_view(), name='reservation-detail')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    url(r'^profile/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name='user_profile'),
    url(r'^profile/teacher/(?P<pk>\d+)/edit/$', views.TeacherProfileUpdateView.as_view(), name='teacher_update_profile'),
    url(r'^profile/student/(?P<pk>\d+)/edit/$', views.StudentProfileUpdateView.as_view(), name='student_update_profile'),
    url(r'^search-teacher/', views.SearchTeacherView.as_view(), name='search_teacher'),
    url(r'^teacher-results/', views.TeacherResultView.as_view(), name='teacher_result'),
    url(r'^ajax/load-subjects/', views.loadSubjects, name='ajax_load_subject'),
    url(r'^teacher/(?P<pk>\d+)$', views.TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^reservation/(?P<pk>\d+)$', views.ReservationDetailView.as_view(), name='reservation')
]

theme/models.py
from django.db import models

# Create your models here.

FAQS_CATEGORIES_CHOICES = (
    (1, 'Para estudiantes y padres de familia'),
    (2, 'Para docentes expertos')
)


class Faq(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False, verbose_name='Pregunta')
    description = models.TextField(blank=False, null=False, verbose_name='Respuesta')
    active = models.BooleanField(default=True, verbose_name='Visible')
    category = models.IntegerField(default=1, blank=False, choices=FAQS_CATEGORIES_CHOICES, verbose_name='Categoría')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False, verbose_name='Creado')

    class Meta:
        verbose_name = 'Pregunta Frecuente'
        verbose_name_plural = 'Preguntas Frecuentes'
        ordering = ['category', 'created_at']
        indexes = [
            models.Index(fields=['title'], name='faq_title_idx')
        ]

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title


class GeneralSetting(models.Model):
    key = models.CharField(max_length=150, verbose_name='Llave', db_index=True, unique=True)
    value = models.CharField(verbose_name='Valor', max_length=255)
    description = models.CharField(verbose_name='Descripción', max_length=255)

    class Meta:
        verbose_name = 'Configuración General'
        verbose_name_plural = 'Configuraciones Generales'
        indexes = (
            models.Index(fields=['key'], name='general_setting_idx'),
        )

    def __str__(self):
        return self.description

    def __unicode__(self):
        return self.description

theme/forms.py
from django import forms


class ContactForm(forms.Form):
    sender_full_name = forms.CharField(
        max_length=150, required=True, help_text='Máximo 150 carácteres', label='Nombres',
        error_messages={'required': 'Por favor digita tu nombre', 'max_length': 'Máximo 150 carácteres'},
        widget=forms.TextInput(attrs={'class': 'sm-form-control required', 'id': 'widget-contact-form-name'}))
    sender_email = forms.EmailField(
        required=True, error_messages={'required': 'Por favor digita un correo'}, label='Correo',
        widget=forms.TextInput(attrs={'class': 'sm-form-control required email', 'id': 'widget-contact-form-email'}))
    sender_phone = forms.CharField(
        max_length=20, required=False, label='Teléfono',
        widget=forms.TextInput(attrs={'class': 'sm-form-control required'}))
    sender_city = forms.CharField(
        max_length=20, required=True, label='Ciudad',
        widget=forms.TextInput(attrs={'class': 'sm-form-control required'}))
    subject = forms.CharField(
        max_length=150, required=False, label='Asunto',
        widget=forms.TextInput(attrs={'class': 'sm-form-control'}))
    message = forms.CharField(
        required=True, label='Mensaje',
        widget=forms.Textarea(attrs={'class': 'sm-form-control required', 'id': 'widget-contact-form-message'}),
        error_messages={'required': 'No no has dicno nada, por favor escribe tu mensaje'})

theme/views.py
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic

from tuto_experts import utils as tuto_utils
from users.forms import StudentSignUpForm
from users.models import Feedback, Reservation, Student, Subscriber, Teacher

from .forms import ContactForm
from .models import Faq

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = StudentSignUpForm(request.POST)
        if form.is_valid():
            form.save_from_home(request=request)
            response = {
                'message': 'operación exitosa',
                'data': request.scheme + '://' + request.META["HTTP_HOST"] + reverse("registration_complete")
            }
            return JsonResponse(response, status=200)
        else:
            response = {
                'message': 'Por favor complete los datos',
                'data': form.errors
            }
            return JsonResponse(response, status=400)
    else:
        feedbacks = Feedback.objects.all()
        form = StudentSignUpForm()

        context = {
            'form': form,
            'subscribers': Subscriber.objects.filter(is_active=True).count(),
            'teachers': Teacher.objects.filter(user__is_active=True).count(),
            'students': Student.objects.filter(user__is_active=True).count(),
            'reservations': Reservation.objects.filter(status='Transacción aprobada').count(),
            'featured_teachers': Teacher.objects.filter(user__is_active=True).order_by('-rating')[:6],
            'students_feedback': feedbacks.filter(user_type=0)[:2],
            'teachers_feedback': feedbacks.filter(user_type=1)[:2],
        }

    if request.user.is_authenticated() and reverse('auth_login') in request.META.get('HTTP_REFERER'):
        try:
            request.user.student
            return redirect(reverse('users:search_teacher'))
        except ObjectDoesNotExist:
            pass

    return render(request, 'theme/index.html', context)


def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST or None)
        response = {
            'message': 'Por favor complete los datos',
            'success': False
        }

        if contact_form.is_valid():
            subject = contact_form.cleaned_data.get('subject')

            if not subject:
                subject = 'Nuevo mensaje'

            data = {
                'email': contact_form.cleaned_data.get('sender_email'),
                'full_name': contact_form.cleaned_data.get('sender_full_name'),
                'subject': subject,
                'message': contact_form.cleaned_data.get('message'),
                'phone': contact_form.cleaned_data.get('sender_phone'),
                'city': contact_form.cleaned_data.get('sender_city'),
                'site_name': get_current_site(request).name,
                'request': request
            }

            try:
                sent = tuto_utils.send_templated_email(
                    subject='Nuevo mensaje de contacto',
                    recipients=','.join(map(str, settings.EMAIL_CONTACT_TO)),
                    template_path='theme/email/contact_email.html',
                    data=data
                )

                if not isinstance(sent, str):
                    response = {
                        'success': True,
                        'message': '!Gracias! Hemos recibido tus comentarios.'
                    }
                else:
                    raise Exception(sent)
            except Exception:
                response = {
                    'success': False,
                    'message': 'No hemos podido recibir tus comentarios, por favor intenta nuevamete.'
                }

        return JsonResponse(response)
    else:
        contact_form = ContactForm()

    return render(request, 'theme/contact.html', {'contact_form': contact_form})


def AboutUs(request):
    return render(request, 'theme/about.html', {})


def TermsAndConditions(request):
    return render(request, 'theme/terms_conditions.html', {})


def ParticularClasses(request):
    return render(request, 'theme/particular_classes.html', {})


class FaqsIndex(generic.ListView):
    model = Faq
    template_name = 'theme/faqs.html'
    context_object_name = 'faqlist'

    def get_queryset(self):
        return Faq.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super(FaqsIndex, self).get_context_data(**kwargs)
        return context

theme/templates/theme/include/css.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Montserrat:400,700|Crete+Round:400i" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/swiper.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/medical.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/dark.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/medical-icons.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/fonts.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/theme-base-color.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/components/bs-rating.css' %}" type="text/css" />

theme/templates/theme/include/footer.html
{% load static %}
<footer id="footer" style="background-color: #F5F5F5;border-top: 2px solid rgba(0,0,0,0.06);">
  <div class="container" style="border-bottom: 1px solid rgba(0,0,0,0.06);">
    <!-- Footer Widgets
                ============================================= -->
    <div class="footer-widgets-wrap clearfix">
      <div class="col_two_third">
        <div class="widget clearfix">
          <form id="widget-subscribe-form" action="{% url 'users:subscribe' %}" role="form" method="post" class="nobottommargin row clearfix">
            {% csrf_token %}
            <div class="col-lg-9">
              <input type="email" id="widget-subscribe-form-email" name="email" class="sm-form-control required email" placeholder="Digita tu correo para mantenerte actualizado" required>
            </div>
            <div class="input-group-append col-lg-3">
              <button class="button button-rounded button-3d nomargin center btn-block button-green" type="button" id="button-subscribe" onclick="showSubscriptionTC()">Suscribirme
              </button>
            </div>

            <div class="modal fade bs-example-modal-lg" id="subscriptionModal" tabindex="-1" role="dialog" aria-labelledby="mySubscribeModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-body">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title uppercase">
                        Términos y <span> Condiciones de Uso</span>
                      </h4>
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body mx-3">
                      <blockquote>
                        <p>
                          Con el envío de este mensaje autorizo de manera informada, previa y expresa a Tutoexperts. para que trate mis datos personales con fines de contacto comercial o profesional.
                          <div>
                            <input id="checkbox-subscribe" class="checkbox-style" name="accept_tc" type="checkbox">
                            <label for="checkbox-subscribe" class="checkbox-style-1-label checkbox-small">
                              He leído y acepto los <a href="{% url 'terms_and_conditions' %}" target="_blank">términos y condiciones</a>
                            </label>
                          </div>
                        </p>
                        <footer class="blockquote-footer">
                          Adicionalmente, manifiesto que he sido informado (a) de lo que ordena el artículo 12 de la ley 1581 de 2012.
                        </footer>
                      </blockquote>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                      <button type="button" class="btn btn-primary" onclick="sendSubscription()">Suscribirme</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </form>

          <div class="line line-sm"></div>

          <div class="clear-bottommargin-sm clearfix">
            <div class="row">
              <div class="col-lg-3 col-6 bottommargin-sm widget_links">
                <ul>
                  <li>
                    <a href="/">Inicio</a>
                  </li>
                  <li>
                    <a href="{% url 'about' %}">Nosotros</a>
                  </li>
                  <li>
                    <a href="{% url 'faqs' %}">FAQs</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-3 col-6 bottommargin-sm widget_links">
                <ul>
                  {% if user.is_authenticated and user.student %}
                  <li>
                    <a href="{% url 'users:search_teacher' %}">Agendar</a>
                  </li>
                  {% endif %}
                  <li>
                    <a href="{% url 'blog:index' %}">Blog</a>
                  </li>
                  <li>
                    <a href="{% url 'contact' %}">Contacto</a>
                  </li>
                </ul>
              </div>
              {% if user.is_authenticated %}
              <div class="col-lg-3 col-6 bottommargin-sm widget_links">
                <ul>
                  <li>
                    <a href="{% url 'users:user_profile' request.user.pk %}">Perfil</a>
                  </li>
                  <li>
                    <a href="{% url 'auth_password_change' %}">Cambiar contraseña</a>
                  </li>
                  <li>
                    <a href="{% url 'auth_logout' %}">Salir</a>
                  </li>
                </ul>
              </div>
              {% endif %}
              <div class="col-12">
                <img class="col-lg-3" src="{% static 'images/icons/logo_pse.png' %}" alt="Logo PSE" style="max-width: 15%; height: auto;" />
                <img class="col-lg-3" src="{% static 'images/icons/logo_tc.png' %}" alt="Logo PSE" style="max-width: 28%; height: auto;">
                <img class="col-lg-3" src="{% static 'images/icons/logo_baloto.png' %}" alt="Logo PSE" style="max-width: 25%; height: auto;">
                <img class="col-lg-3" src="{% static 'images/icons/logo_efecty.png' %}" alt="Logo PSE" style="max-width: 25%; height: auto;">
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col_one_third col_last">
        <div class="widget clear-bottommargin-sm clearfix">
          <div class="row">
            <div class="col-lg-12 bottommargin-sm">
              <div class="footer-big-contacts footer-contact">
                <span>Llamanos:</span>
                <a href="tel:{{ settings.SITE_CONTACT_PHONE_NUMBER }}">{{ settings.SITE_CONTACT_PHONE_NUMBER }}</a>
                <a href="https://api.whatsapp.com/send?phone={{settings.SITE_WHATSAPP_PHONE_NUMBER|cut:' '|cut:'+'}}" target="_blank" style="color: #098609;">
                  <i class="col-auto fa fa-icon-2x fa-icon-whatsapp"></i>
                </a>
              </div>
            </div>
            <div class="col-lg-12 bottommargin-sm">
              <div class="footer-big-contacts footer-contact">
                <span>Envíanos tus comentarios:</span>
                {{ settings.SITE_INFO_EMAIL | urlize }}
              </div>
            </div>
          </div>
        </div>

        <div class="widget subscribe-widget clearfix">
          <div class="row">
            <div class="col-lg-6 clearfix bottommargin-sm">
              <a href="{{settings.FACEBOOK_SITE}}" target="_blank" class="social-icon si-dark si-colored si-facebook nobottommargin" style="margin-right: 10px;">
                <i class="icon-facebook"></i>
                <i class="icon-line2-social-facebook"></i>
              </a>
              <a href="{{settings.FACEBOOK_SITE}}" target="_blank">
                <small style="display: block; margin-top: 3px;">
                  <strong>Agreganos</strong>
                  <br>en Facebook</small>
              </a>
            </div>
            <div class="col-lg-6 clearfix">
              <a href="{{settings.TWITTER_SITE}}" target="_blank" class="social-icon si-dark si-colored si-twitter nobottommargin" style="margin-right: 10px;">
                <i class="icon-twitter"></i>
                <i class="icon-twitter"></i>
              </a>
              <a href="{{settings.TWITTER_SITE}}" target="_blank">
                <small style="display: block; margin-top: 3px;">
                  <strong>Siguenos</strong>
                  <br>en Twitter</small>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- .footer-widgets-wrap end -->
  </div>
  <!-- Copyrights
            ============================================= -->
  <div id="copyrights" class="nobg">
    <div class="container clearfix">
      <div class="col_half">
        Copyrights &copy; 2018 All Rights Reserved by PAI Inc.
        <br>
        <div class="copyright-links">
          <a href="/">Terminos de Uso</a> /
          <a href="/">Políticas de Privacidad</a>
        </div>
      </div>
      <div class="col_half col_last tright">
        <div class="copyrights-menu copyright-links clearfix">
          <a href="/">Inicio</a>/
          <a href="{% url 'about' %}">Nosotros</a>/
          <a href="/">Profesores</a>/
          <a href="{% url 'blog:index' %}">Blog</a>/
          <a href="{% url 'faqs' %}">FAQs</a>/
          <a href="{% url 'contact' %}">Contacto</a>
        </div>
      </div>
    </div>
  </div>
  <!-- #copyrights end -->
</footer>
<script type="text/javascript">
  $('#widget-subscribe-form').on('keyup keypress', function (e) {
    var keyCode = e.keyCode || e.which;
    if (keyCode === 13) {
      e.preventDefault();
      return false;
    }
  });
</script>
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/components/radio-checkbox.css' %}" type="text/css" />
<style>
  .footer-contact {
    font-size: 2.1vh;
  }
</style>
{% endblock %}

theme/templates/theme/include/footerjs.html
{% load static %}

<!-- External JavaScripts
	============================================= -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/star-rating.js' %}"></script>
<!-- Footer Scripts
============================================= -->
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/tuto_expert.js' %}"></script>

theme/templates/theme/include/topbar.html
{% load static %}
<!-- Inluide Jqyery -->
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tuto_expert.js' %}"></script>
{% endblock %}
<!-- Top Bar
============================================= -->
<div id="top-bar">
  <div class="container clearfix">
    <div class="col_half d-none d-md-block nobottommargin">
      <!-- Top Links
        ============================================= -->
      <div class="top-links">
        <ul>
          {% comment %}
          <li>
            <a href="/"><i class="icon-time"></i> Horarios de atención</a>
          </li>
          {% endcomment %}
          <li>
            <a href="tel:{{ settings.SITE_CONTACT_PHONE_NUMBER }}"><i class="icon-phone3"></i>{{ settings.SITE_CONTACT_PHONE_NUMBER }}</a>
          </li>
          <li>
            <a href="mailto:{{ settings.SITE_INFO_EMAIL }}" class="nott"><i class="icon-envelope2"></i> {{ settings.SITE_INFO_EMAIL }}</a>
          </li>
        </ul>
      </div>
      <!-- .top-links end -->
    </div>
    <div class="col_half col_last fright nobottommargin">
      <!-- Top Links
       ============================================= -->
      <div class="top-links">
        <ul>
          <li>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'auth_login' %}" data-offset="100" data-easing="easeInOutExpo" data-speed="1200" class="button-green" style="color:#fff;">
              <i class="icon-line2-login"></i> INICIAR SESIÓN
            </a> {% else %}
            <a href="{% url 'auth_logout' %}" data-offset="100" data-easing="easeInOutExpo" data-speed="1200" class="button-green" style="color:#fff;">
              <i class="icon-line2-logout"></i> SALIR
            </a> {% endif %}
          </li>
        </ul>
      </div>
      <!-- .top-links end -->
    </div>
  </div>
</div>

theme/templates/theme/include/topnavbar.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<header id="header">
  <div id="header-wrap">
    <div class="container-fluid clearfix bg-white">
      <div id="primary-menu-trigger">
        <i class="icon-reorder"></i>
      </div>
      <!-- Logo
					============================================= -->
      <div id="logo">
        <a href="{% url 'home' %}" class="standard-logo">
          <img src="{% static 'images/logo-tuto-experts.png' %}" alt="Tuto Experts">
        </a>
        <a href="{% url 'home' %}" class="retina-logo">
          <img src="{% static 'images/logo-tuto-experts.png' %}" alt="Tuto Experts">
        </a>
      </div>
      <!-- #logo end -->
      <!-- Primary Navigation
					============================================= -->
      <nav id="primary-menu" class="style-3">
        <ul>
          <li class="{% if request.get_full_path == '/' %} current {% endif %}">
            <a href="{% url 'home' %}">
              <div>Inicio</div>
            </a>
          </li>
          {% if user.is_authenticated and user.student %}
          <li class="{% if '/users/search' in request.get_full_path or '/users/teacher' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'users:search_teacher' %}">
              <div>Reservar</div>
            </a>
          </li>
          {% endif %}
          {% if not user.is_authenticated %}
          <li class="{% if '/register/student' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'student_signup' %}">
              <div class="uppercase">Solicita tu clase aquí</div>
            </a>
          </li>

          <li class="{% if '/register/teacher' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'teacher_signup' %}">
              <div class="uppercase">Registrate como tutor</div>
            </a>
          </li>
          {% endif %}
          <li class="{% if '/subjects/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'subjects' %}">
              <div>Materias</div>
            </a>
          </li>
          <li class="{% if '/about' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'about' %}">
              <div>Nosotros</div>
            </a>
          </li>
          <li class="{% if '/faqs/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'faqs' %}">
              <div>FAQs</div>
            </a>
          </li>
          <li class="{% if '/blog/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'blog:index' %}">
              <div>Blog</div>
            </a>
          </li>
          <li class="{% if '/contact/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'contact' %}">
              <div>Contacto</div>
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="{% if '/profile/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'users:user_profile' request.user.pk %}">
              <div>{{user.get_full_name|truncatewords:1}}</div>
            </a>
            <ul>
              <li>
                <a href="{% if user.teacher %}{% url 'users:teacher_update_profile'  request.user.pk %}{% else %}{% url 'users:student_update_profile'  request.user.pk %}{% endif %}">
                  <div>Editar Perfil</div>
                </a>
              </li>

              {% if user.teacher %}
              <li>
                <a href="{% url 'blog:create' %}">
                  <div>Nueva publicación</div>
                </a>
              </li>
              {% endif %}
              <li>
                <a href="{% url 'auth_password_change' %}">Cambiar contraseña</a>
              </li>
              <li>
                <a href="{% url 'auth_logout' %}">Salir</a>
              </li>
            </ul>
          </li>

          {% comment %}
          {% else %}
          <li class="{% if '/login/' in request.get_full_path %} current {% endif %}">
            <a href="{% url 'auth_login' %}">
              <div>Iniciar Sesión</div>
            </a>
          </li>
          {% endcomment %}


          {% endif %}
        </ul>
      </nav>
      <!-- #primary-menu end -->
    </div>
  </div>
</header>