blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^create/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$', views.BlogDetail.as_view(), name='detail')
]

tuto_experts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.default.views import RegistrationView

from theme import views
from users import forms, views as userViews

admin.site.te_header = "Tuto Experts"
admin.site.site_title = "Administrador Tuto Experts"
admin.site.index_title = "Bienvenido"


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^checkout/', userViews.CheckoutView.as_view(), name='checkout'),
    url(r'^payment_response/', userViews.PaymentResponseView.as_view(), name='payment_response'),
    url(r'^payment_confirmation/', userViews.payment_confirmation, name='payment_confirmation'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.FaqsIndex.as_view(), name='faqs'),
    url(r'^feedback/', userViews.FeedbackIndex.as_view(), name='feedback'),
    url(r'^about-us/', views.AboutUs, name='about'),
    url(r'^subjects/', userViews.SubjectIndex.as_view(), name='subjects'),
    url(r'^terms-and-conditions/', views.TermsAndConditions, name='terms_and_conditions'),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/register/student/', RegistrationView.as_view(form_class=forms.StudentSignUpForm), name='student_signup'),
    url(r'^accounts/register/teacher/', userViews.TeacherRegistrationView.as_view(), name='teacher_signup'),
    url(r'^accounts/social/register/', userViews.social_registration, name='social_register'),
    url(r'^accounts/social/login/', userViews.social_login, name='social_login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^config/', admin.site.urls),
    url(r'^particular-classes/', views.ParticularClasses, name='particular_classes'),
    url(r'^reservation-confirmation/(?P<reservation_code>\w+)/$', userViews.ReservationConfirmationView.as_view(), name='reservation-confirmation'),
    url(r'^reservation-detail/(?P<reservation_code>\w+)/$', userViews.ReservationResumeDetailView.as_view(), name='reservation-detail')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    url(r'^profile/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name='user_profile'),
    url(r'^profile/teacher/(?P<pk>\d+)/edit/$', views.TeacherProfileUpdateView.as_view(), name='teacher_update_profile'),
    url(r'^profile/student/(?P<pk>\d+)/edit/$', views.StudentProfileUpdateView.as_view(), name='student_update_profile'),
    url(r'^search-teacher/', views.SearchTeacherView.as_view(), name='search_teacher'),
    url(r'^teacher-results/', views.TeacherResultView.as_view(), name='teacher_result'),
    url(r'^ajax/load-subjects/', views.loadSubjects, name='ajax_load_subject'),
    url(r'^teacher/(?P<pk>\d+)$', views.TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^reservation/(?P<pk>\d+)$', views.ReservationDetailView.as_view(), name='reservation')
]

users/models.py
import hashlib
import json
import re
import uuid
from datetime import timedelta

import requests
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from registration.signals import user_registered
from unidecode import unidecode


from .signals import *

# Create your models here.
LEVEL_CHOICES = (
    (1, 'Ed. Básica'),
    (2, 'Ed. Media'),
    (3, 'Ed. Superior'),
    (4, 'Idiomas')
)

CLASS_MODE_CHOICES = (
    (1, 'Presencial'),
    (2, 'Virtual'),
    (3, 'Ambos')
)

CLASS_MODE_CHOICES_FOR_SEARCH = (
    (1, 'Presencial'),
    (2, 'Virtual')
)

DAYS_OF_WEEK_CHOICES = (
    (1, 'Lunes'),
    (2, 'Martes'),
    (3, 'Miercoles'),
    (4, 'Jueves'),
    (5, 'Viernes'),
    (6, 'Sabado'),
    (7, 'Domingo')
)

PSE_CUSTOMER_TYPE = (
    ('N', 'PERSONA NATURAL'),
    ('J', 'PERSONA JURIDICA')
)

PSE_CUSTOMER_ID_TYPE = (
    ('CC', ' CÉDULA DE CUIDADANÍA'),
    ('CE', 'CÉDULA DE EXTRANJERÍA'),
    ('NIT', 'NÚMERO DE IDENTIFICACIÓN TRIBUTARIO'),
    ('TI', 'TARJETA DE IDENTIDAD'),
    ('PP', 'PASAPORTE'),
    ('IDC', 'IDENTIFICADOR ÚNICO DE CLIENTE (ID ÚNICO DE SERVICIO PÚBLICO)'),
    ('CEL', 'IDENTIFICADOR POR LÍNEA MÓVIL'),
    ('RC', 'REGISTRO CIVIL DE NACIMIENTO'),
    ('DE', 'DOCUMENTO DE INDETIFICACIÓN EXTRANJERO')
)

PAYMENT_STATUS_CHOICES = (
    (1, 'GENERADO'),
    (2, 'PAGADO')
)


def profile_photo_folder(instance, filename):
    return '/'.join(['user', 'photos', str(instance.user.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')
    birth_date = models.DateField(verbose_name='Fecha de nacimiento', auto_now=False, auto_now_add=False, blank=True, null=True)
    photo = models.ImageField(verbose_name='Foto', upload_to=profile_photo_folder, blank=True, null=True)
    phone = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=50)
    preferred_subject = models.CharField(verbose_name='Materia de interés', blank=True, null=True, max_length=255)

    class Meta:
        verbose_name = 'Estudiante'
        verbose_name_plural = 'Estudiantes'

    def __str__(self):
        return self.user.email


class Teacher(models.Model):

    def attachment_folder(self, filename):
        return '/'.join(['teacher', 'attachments', str(self.user.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')
    career = models.CharField(blank=False, null=False, max_length=150, verbose_name='Profesión')
    biography = models.TextField(verbose_name='Acerca de', blank=True, null=True)
    phone = models.BigIntegerField(verbose_name='Teléfono', blank=True, null=True)
    id_number = models.BigIntegerField(verbose_name='Identificación', blank=False, null=False, db_index=True, help_text='Número de identificación', unique=True)
    rating = models.FloatField(default=0)
    work_mode = models.IntegerField(verbose_name='Modo de trabajo', choices=CLASS_MODE_CHOICES)
    skype_user = models.CharField(max_length=50, verbose_name='Skype')
    facebook_link = models.URLField(verbose_name='Facebook', blank=True, null=True)
    instagram_link = models.URLField(verbose_name='Instagram', blank=True, null=True)
    twitter_link = models.URLField(verbose_name='Twitter', blank=True, null=True)
    linkedin_link = models.URLField(verbose_name='LinkedIn', blank=True, null=True)
    google_link = models.URLField(verbose_name='Google+', blank=True, null=True)
    photo = models.ImageField(verbose_name='Foto', upload_to=profile_photo_folder, blank=True, null=True)
    juditial_past = models.FileField(verbose_name='Antecedentes judiciales', upload_to=attachment_folder, blank=True, null=True)
    certificate = models.FileField(verbose_name='Certificado pedagógico', upload_to=attachment_folder, blank=True, null=True)

    class Meta:
        verbose_name = 'Docente'
        verbose_name_plural = 'Docentes'

    def __str__(self):
        return self.user.get_full_name()


class Subscriber(models.Model):
    email = models.EmailField(unique=True, db_index=True)
    is_active = models.BooleanField(default=True, verbose_name='Activo')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False, verbose_name='Creado')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email


class Area(models.Model):
    name = models.CharField(max_length=200, blank=False, verbose_name='Nombre')
    level = models.IntegerField(choices=LEVEL_CHOICES, blank=False, verbose_name='Nivel')
    description = models.TextField(verbose_name='Descripción', blank=True, null=True)
    min_price = models.IntegerField(blank=False, verbose_name='Precio Min')
    max_price = models.IntegerField(blank=False, verbose_name='Precio Max')
    increment = models.IntegerField(blank=False, verbose_name='Incremento', default=1000)
    active = models.BooleanField(default=True, verbose_name='Activo')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Subject(models.Model):
    def images_folder(self, filename):
        return '/'.join(['subject', 'images', str(self.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])

    area = models.ForeignKey(Area, related_name='area_subjects', verbose_name='Area', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name='Nombre')
    description = models.TextField(verbose_name='Descripción', blank=True, null=True)
    image = models.ImageField(verbose_name='Imagen', blank=True, null=True, upload_to=images_folder)
    active = models.BooleanField(default=True, verbose_name='Activo')
    visible = models.BooleanField(default=False, verbose_name='Visible', help_text='Visible en la sección de materias')

    class Meta:
        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'
        ordering = ['name']

    def __str__(self):
        return self.name


# Clase para almacenar la informacion de los pagos a los docentes (archivos de excel generados para pagar por parte de tuto experts)
class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user', on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(verbose_name='Estado', choices=PAYMENT_STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True, editable=False, verbose_name='Fecha')

    def __str__(self):
        return '%s, %s' % (str(self.pk), self.created_at.strftime('%A %d %B, %Y %I:%M %p'))

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'


class Reservation(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='student_reservations', verbose_name='Estudiante', on_delete=models.CASCADE)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='teacher_reservations', verbose_name='Docente', on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, related_name='subject_reservations', verbose_name='Materia', on_delete=models.CASCADE)
    topic = models.TextField(verbose_name='Tema')
    duration = models.IntegerField(verbose_name='Duración')
    start_datetime_class = models.DateTimeField(verbose_name='Fecha y Hora Inicio')
    end_datetime_class = models.DateTimeField(verbose_name='Fecha y Hora Fin')
    mode = models.IntegerField(choices=CLASS_MODE_CHOICES, verbose_name='Modalidad')
    price = models.FloatField(verbose_name='Valor total')
    amount_to_paid = models.FloatField(default=0)
    paid = models.BooleanField(default=False, help_text='Pagada al docente', verbose_name='Pagado a docente')
    address = models.TextField(blank=True, null=True)
    edited_at = models.DateTimeField(auto_now_add=False, auto_now=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False)
    payment = models.ForeignKey(Payment, on_delete=models.DO_NOTHING, blank=True, null=True)
    payment_proof = models.CharField(blank=True, null=True, max_length=50, verbose_name='Número de transacción', help_text='Referencia de pago (cuando se pague al docente)')
    confirmed = models.BooleanField(db_index=True, default=False, verbose_name='Confirmado por Estudiante')
    # Campos de payu
    reference_code = models.CharField(max_length=50, verbose_name='Código de referencia', blank=True, null=True)
    order_id = models.BigIntegerField(verbose_name='Orden Payu', db_index=True, help_text='Número de orden generado por Payu', default=1)
    transaction_id = models.CharField(max_length=50, verbose_name='No Transacción', db_index=True, default='')
    status = models.CharField(max_length=100, verbose_name='Estado', db_index=True, default='Pendiente')
    trazability_code = models.CharField(max_length=50, verbose_name='Código de Trazabilidad', db_index=True, default='')
    authorization_code = models.CharField(max_length=50, verbose_name='Código de Autorización', blank=True, null=True)
    url_payment_pdf = models.URLField(verbose_name='PDF', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')
    url_payment_web = models.URLField(verbose_name='WEB', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')
    reference_number = models.BigIntegerField(verbose_name='No Referencia', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')

    def __str__(self):
        return self.topic

    class Meta:
        ordering = ['created_at']
        verbose_name = 'Reserva'
        verbose_name_plural = 'Reservas'

users/templates/users/feedback_form.html
{% load widget_tweaks %}

<div class="fixed-menu">
    <div data-toggle="modal" class="button button-small button-rounded button-3d button-green" data-target="#feedback-modal" role="button">
        <i class="icon-comment-alt"></i> Mi experiencia
    </div>
</div>

<div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-body">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Enviar mis comentarios</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" role="form" method="post">
                        {% csrf_token %}
                        <input name="rating" value="1" class="rating" data-show-caption="false" data-step="1" data-show-clear="false" data-size="sm" max="5" min="1" required id="id_rating" />

                        {% render_field form.text %}

                        <button class="button button-3d button-rounded button-green d-sm-inline-block" type="submit" style="margin-top:15px;">
                            <i class="icon-line2-paper-plane"></i> Enviar
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/users/search_teacher.html
{% extends "base.html" %}
<!-- archivos staticos -->
{% load static i18n widget_tweaks %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Búsqueda {% endblock title %}
<!-- Contenido -->
{% block content %}
<section id="slider" class="slider-element full-screen">

	<div class="row full-screen">

		<div class="col-lg-7 col-md-6 full-screen center nopadding" style="background: url('{% static 'images/slider/4.jpg' %}') center center no-repeat; background-size: cover;">
			<div class="vertical-middle dark center clearfix" style="z-index: 2;">

				<div class="emphasis-title nobottommargin">
					<h1>
						<span class="text-rotater nocolor" data-separator="|" data-rotate="fadeIn" data-speed="6000">
							<span class="t-rotate t700 font-body opm-medium-word">Mejores tutores.|Tú horario.|Cuando lo necesites.</span>
						</span>
					</h1>
				</div>

			</div>
			<div class="video-wrap" style="position: absolute; z-index:1; height:100%;">
				<div class="video-overlay" style="background-color: rgba(0,0,0,0.2);"></div>
			</div>
		</div>

		<div class="col-lg-5 col-md-6 full-screen" style="background-color: #F5F5F5;">
			<div class="vertical-middle" data-loader="button">
				<div class="col-padding">
					<div class="heading-block nobottomborder bottommargin-sm">
						<h2 style="line-height: 1;font-size: 20px;">Escoge el tutor</h2>
					</div>

					<form method="post" id="search_teacher_form" data-subjects-url="{% url 'users:ajax_load_subject' %}" class="nobottommargin" data-animate="fadeInUp" data-delay="600">
						{% csrf_token %}

						<div class="col_full required">
							<label for="{{ form.area.id_for_label }}" class="required">
								{{ form.area.label }}:
							</label>
							{% render_field form.area class+="sm-form-control required" %}
						</div>
						<div class="col_full required">
							<label for="{{ form.subject.id_for_label }}" class="required">
								{{ form.subject.label }}:
							</label>
							{% render_field form.subject class+="sm-form-control required" %}
						</div>

						<div class="col_half required">
							<label for="{{ form.class_mode.id_for_label }}" class="required">
								{{ form.class_mode.label }}:
							</label>
							{% render_field form.class_mode class+="sm-form-control required" %}
						</div>

						<div class="col_half col_last required">
							<label for="{{ form.duration.id_for_label }}" class="required">
								{{ form.duration.label }} (Horas):
							</label>
							{% render_field form.duration class+="sm-form-control required" value="1" min="1" step="1" %}
						</div>

						<div class="col_half required">
							<label for="{{ form.class_date.id_for_label }}" class="required">
								{{ form.class_date.label }}:
							</label>
							{{form.class_date}}
						</div>

						<div class="col_half col_last required">
							<label for="{{ form.class_time.id_for_label }}" class="required">
								{{ form.class_time.label }}:
							</label>
							{{form.class_time}}
						</div>

						<div class="col_full nobottommargin center">
							<button type="submit" class="button button-dark button-3d button-rounded button-green nomargin" value="submit">Buscar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</section>

{% endblock content %}
<!-- adicional css -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/components/datepicker.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/components/jquery.timepicker.min.css' %}" type="text/css" />
{% endblock %}
<!-- adicional js -->
{% block extra_js %}
<script src="{% static 'js/components/datepicker.js' %}"></script>
<script src="{% static 'js/components/jquery.timepicker.min.js' %}"></script>

<script>
	$(function () {
		$('.datetimepicker').datepicker({
			format: 'yyyy-mm-dd',
			language: 'es',
			autoclose: true,
			todayBtn: "linked",
			todayHighlight: true,
			startDate: new Date()
		})

		$('.timepicker').timepicker({
			timeFormat: 'hh:mm p',
			dynamic: false,
			dropdown: true,
			scrollbar: false
		})

		$("#id_area").change(function () {
			getSubjects($(this).val())
		})

		var selectedArea = $('#id_area').val()
		if (selectedArea) getSubjects(selectedArea)

		/** duration validations & events */
		$('#id_duration').keypress(function (event) {
			return (event.charCode >= 46 && event.charCode <= 57) || event.charCode == 8
		})

		$('#id_duration').on('input', function () {
			var value = $(this).val()

			if (!value) $(this).val(1)
		})

		var pre_selected_date = '{{ request.session.reservation_date }}'
		if (pre_selected_date) {
			var date_time = pre_selected_date.split(' ')
			$('.datetimepicker').val(date_time[0])
			$('.timepicker').val(date_time[1] + ' ' + date_time[2])
		}
	})

	function getSubjects(areaId) {
		var url = $("#search_teacher_form").attr("data-subjects-url");
		$.ajax({
			url: url,
			data: {
				'area': areaId
			},
			success: function (data) {
				$("#id_subject").html(data)

				pre_selected_subject = '{{ request.session.reservation_subject }}'
				if (pre_selected_subject) $('#id_subject').val(pre_selected_subject)
			}
		})
	}
</script>
{% endblock %}

users/templates/users/subject_index.html
{% extends "theme/base_theme.html" %}
<!-- archivos staticos -->
{% load static %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Materias {% endblock title %}
<!-- Contenido -->
{% block content %}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <div class="fancy-title title-dotted-border title-center">
                <h4>En
                    <span>tutoexperts</span>
                    puedes encontrar clases particulares virtuales o a domicilio
                    {% if not user.is_authenticated %}
                    <span class="dropdown show">
                        <a href="#" role="button" id="registerDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Regístrate
                        </a>

                        <div class="dropdown-menu" aria-labelledby="registerDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'student_signup' %}">
                                <div class="uppercase">Solicita tu clase aquí</div>
                            </a>

                            <a class="dropdown-item" href="{% url 'teacher_signup' %}">
                                <div class="uppercase">Registrate como tutor</div>
                            </a>
                        </div>
                    </span>
                    {% else %} Regístrate {% endif %} y encuentra tutores expertos en:
                </h4>
            </div>

            <div class="portfolio grid-container portfolio-2 clearfix">
                {% for subject in subjects %}
                <article class="portfolio-item pf-media pf-icons">
                    <div class="portfolio-desc">
                        <h3><a href="#">{{subject.name}}</a></h3>
                        <span><a href="#">{{subject.area.get_level_display}}</a>, <a href="#">{{subject.area.name}}</a></span>
                    </div>
                    <div class="portfolio-image">
                        <a href="#">
                            <img src="{% if not subject.image %}{% static 'images/sections/black_white_books.jpg' %}{% else %}{{ subject.image.url }}{% endif %}" alt="{{subject.name}}">
                        </a>
                        <div class="portfolio-overlay">
                            <a class="center-icon" data-lightbox="image" href="{% if not subject.image %}{% static 'images/sections/black_white_books.jpg' %}{% else %}{{ subject.image.url }}{% endif %}">
                                <i class="icon-line-plus"></i>
                            </a>
                        </div>
                    </div>
                </article>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/subjects_dropdown_list.html
<option value="">---------</option>
{% for subject in subjects %}
<option value="{{ subject.pk }}">{{ subject.name }}</option>
{% endfor %}

users/templates/users/teachers_result.html
{% extends "base.html" %}
<!-- archivos staticos -->
{% load static i18n l10n %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Perfil {% endblock title %}
<!-- Contenido -->
{% block content %}
<section id="content">

	<div class="content-wrap">

		<div class="container clearfix">
			{% if skills %}

			<div class="heading-block center">
				<h2>Mejores Docentes</h2>
				<span>encuentra el docente que mas se ajuste a tu necesidad</span>
			</div>

			<div class="row clearfix">
				{% for skill in skills %}
				<div class="col-lg-6 bottommargin">
					<div class="team team-list clearfix">
						<div class="team-image">
							<a href="{% url 'users:teacher_detail' skill.teacher.teacher.pk %}" class="more-link"><img src="{% if not skill.teacher.teacher.photo %}{% static 'images/tutors/avatar.svg' %}{% else %}{{ skill.teacher.teacher.photo.url }}{% endif %}"></a>
						</div>
						<div class="team-desc">
							<div class="team-title">
								<h4>{{ skill.teacher.username }}</h4><span>{{ skill.teacher.career }}</span>
							</div>
							<div class="team-content">
								<p>{{ skill.teacher.teacher.biography|default_if_none:""|truncatewords:30 }}</p>
							</div>

							<input class="rating" value="{{ skill.teacher.teacher.rating|stringformat:'.1f' }}" data-size="xs" readonly data-show-caption="false" data-show-clear="false">

							{% if skill.teacher.teacher.facebook_link %}
							<a href="{{ skill.teacher.teacher.facebook_link }}" target="_blank" class="social-icon si-rounded si-small si-light si-facebook">
								<i class="icon-facebook"></i>
								<i class="icon-facebook"></i>
							</a>
							{% endif %}
							{% if skill.teacher.teacher.twitter_link %}
							<a href="{{ skill.teacher.teacher.twitter_link }}" target="_blank" class="social-icon si-rounded si-small si-light si-twitter">
								<i class="icon-twitter"></i>
								<i class="icon-twitter"></i>
							</a>
							{% endif %}
							{% if skill.teacher.teacher.google_link %}
							<a href="{{ skill.teacher.teacher.google_link }}" target="_blank" class="social-icon si-rounded si-small si-light si-gplus">
								<i class="icon-gplus"></i>
								<i class="icon-gplus"></i>
							</a>
							{% endif %}
							{% if skill.teacher.teacher.linkedin_link %}
							<a href="{{ skill.teacher.teacher.linkedin_link }}" target="_blank" class="social-icon si-rounded si-small si-light si-linkedin">
								<i class="icon-linkedin"></i>
								<i class="icon-linkedin"></i>
							</a>
							{% endif %}
							{% if skill.teacher.teacher.instagram_link %}
							<a href="{{ skill.teacher.teacher.instagram_link }}" target="_blank" class="social-icon si-rounded si-small si-light si-instagram">
								<i class="icon-instagram"></i>
								<i class="icon-instagram"></i>
							</a>
							{% endif %}

						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			{% else %}
			<div class="heading-block center">
				<h2><i class="fa fa-icon-frown-o fa-icon-4x"></i></h2>
				<span>No hay docentes disponibles para ayudarte, intenta con otros parámetros</span>
			</div>
			{% endif %}

		</div>
	</div>
</section>
{% endblock content %}