blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^create/$', views.BlogCreate.as_view(), name='create'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$', views.BlogDetail.as_view(), name='detail')
]

tuto_experts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.default.views import RegistrationView

from theme import views
from users import forms, views as userViews

admin.site.te_header = "Tuto Experts"
admin.site.site_title = "Administrador Tuto Experts"
admin.site.index_title = "Bienvenido"


urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^checkout/', userViews.CheckoutView.as_view(), name='checkout'),
    url(r'^payment_response/', userViews.PaymentResponseView.as_view(), name='payment_response'),
    url(r'^payment_confirmation/', userViews.payment_confirmation, name='payment_confirmation'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faqs/', views.FaqsIndex.as_view(), name='faqs'),
    url(r'^feedback/', userViews.FeedbackIndex.as_view(), name='feedback'),
    url(r'^about-us/', views.AboutUs, name='about'),
    url(r'^subjects/', userViews.SubjectIndex.as_view(), name='subjects'),
    url(r'^terms-and-conditions/', views.TermsAndConditions, name='terms_and_conditions'),
    url(r'^users/', include('users.urls')),
    url(r'^accounts/register/student/', RegistrationView.as_view(form_class=forms.StudentSignUpForm), name='student_signup'),
    url(r'^accounts/register/teacher/', userViews.TeacherRegistrationView.as_view(), name='teacher_signup'),
    url(r'^accounts/social/register/', userViews.social_registration, name='social_register'),
    url(r'^accounts/social/login/', userViews.social_login, name='social_login'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^config/', admin.site.urls),
    url(r'^particular-classes/', views.ParticularClasses, name='particular_classes'),
    url(r'^reservation-confirmation/(?P<reservation_code>\w+)/$', userViews.ReservationConfirmationView.as_view(), name='reservation-confirmation'),
    url(r'^reservation-detail/(?P<reservation_code>\w+)/$', userViews.ReservationResumeDetailView.as_view(), name='reservation-detail')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    url(r'^profile/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name='user_profile'),
    url(r'^profile/teacher/(?P<pk>\d+)/edit/$', views.TeacherProfileUpdateView.as_view(), name='teacher_update_profile'),
    url(r'^profile/student/(?P<pk>\d+)/edit/$', views.StudentProfileUpdateView.as_view(), name='student_update_profile'),
    url(r'^search-teacher/', views.SearchTeacherView.as_view(), name='search_teacher'),
    url(r'^teacher-results/', views.TeacherResultView.as_view(), name='teacher_result'),
    url(r'^ajax/load-subjects/', views.loadSubjects, name='ajax_load_subject'),
    url(r'^teacher/(?P<pk>\d+)$', views.TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^reservation/(?P<pk>\d+)$', views.ReservationDetailView.as_view(), name='reservation')
]

users/models.py
import hashlib
import json
import re
import uuid
from datetime import timedelta

import requests
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from registration.signals import user_registered
from unidecode import unidecode


from .signals import *

# Create your models here.
LEVEL_CHOICES = (
    (1, 'Ed. Básica'),
    (2, 'Ed. Media'),
    (3, 'Ed. Superior'),
    (4, 'Idiomas')
)

CLASS_MODE_CHOICES = (
    (1, 'Presencial'),
    (2, 'Virtual'),
    (3, 'Ambos')
)

CLASS_MODE_CHOICES_FOR_SEARCH = (
    (1, 'Presencial'),
    (2, 'Virtual')
)

DAYS_OF_WEEK_CHOICES = (
    (1, 'Lunes'),
    (2, 'Martes'),
    (3, 'Miercoles'),
    (4, 'Jueves'),
    (5, 'Viernes'),
    (6, 'Sabado'),
    (7, 'Domingo')
)

PSE_CUSTOMER_TYPE = (
    ('N', 'PERSONA NATURAL'),
    ('J', 'PERSONA JURIDICA')
)

PSE_CUSTOMER_ID_TYPE = (
    ('CC', ' CÉDULA DE CUIDADANÍA'),
    ('CE', 'CÉDULA DE EXTRANJERÍA'),
    ('NIT', 'NÚMERO DE IDENTIFICACIÓN TRIBUTARIO'),
    ('TI', 'TARJETA DE IDENTIDAD'),
    ('PP', 'PASAPORTE'),
    ('IDC', 'IDENTIFICADOR ÚNICO DE CLIENTE (ID ÚNICO DE SERVICIO PÚBLICO)'),
    ('CEL', 'IDENTIFICADOR POR LÍNEA MÓVIL'),
    ('RC', 'REGISTRO CIVIL DE NACIMIENTO'),
    ('DE', 'DOCUMENTO DE INDETIFICACIÓN EXTRANJERO')
)

PAYMENT_STATUS_CHOICES = (
    (1, 'GENERADO'),
    (2, 'PAGADO')
)


def profile_photo_folder(instance, filename):
    return '/'.join(['user', 'photos', str(instance.user.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])


class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')
    birth_date = models.DateField(verbose_name='Fecha de nacimiento', auto_now=False, auto_now_add=False, blank=True, null=True)
    photo = models.ImageField(verbose_name='Foto', upload_to=profile_photo_folder, blank=True, null=True)
    phone = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=50)
    preferred_subject = models.CharField(verbose_name='Materia de interés', blank=True, null=True, max_length=255)

    class Meta:
        verbose_name = 'Estudiante'
        verbose_name_plural = 'Estudiantes'

    def __str__(self):
        return self.user.email


class Teacher(models.Model):

    def attachment_folder(self, filename):
        return '/'.join(['teacher', 'attachments', str(self.user.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')
    career = models.CharField(blank=False, null=False, max_length=150, verbose_name='Profesión')
    biography = models.TextField(verbose_name='Acerca de', blank=True, null=True)
    phone = models.BigIntegerField(verbose_name='Teléfono', blank=True, null=True)
    id_number = models.BigIntegerField(verbose_name='Identificación', blank=False, null=False, db_index=True, help_text='Número de identificación', unique=True)
    rating = models.FloatField(default=0)
    work_mode = models.IntegerField(verbose_name='Modo de trabajo', choices=CLASS_MODE_CHOICES)
    skype_user = models.CharField(max_length=50, verbose_name='Skype')
    facebook_link = models.URLField(verbose_name='Facebook', blank=True, null=True)
    instagram_link = models.URLField(verbose_name='Instagram', blank=True, null=True)
    twitter_link = models.URLField(verbose_name='Twitter', blank=True, null=True)
    linkedin_link = models.URLField(verbose_name='LinkedIn', blank=True, null=True)
    google_link = models.URLField(verbose_name='Google+', blank=True, null=True)
    photo = models.ImageField(verbose_name='Foto', upload_to=profile_photo_folder, blank=True, null=True)
    juditial_past = models.FileField(verbose_name='Antecedentes judiciales', upload_to=attachment_folder, blank=True, null=True)
    certificate = models.FileField(verbose_name='Certificado pedagógico', upload_to=attachment_folder, blank=True, null=True)

    class Meta:
        verbose_name = 'Docente'
        verbose_name_plural = 'Docentes'

    def __str__(self):
        return self.user.get_full_name()


class Subscriber(models.Model):
    email = models.EmailField(unique=True, db_index=True)
    is_active = models.BooleanField(default=True, verbose_name='Activo')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False, verbose_name='Creado')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email


class Area(models.Model):
    name = models.CharField(max_length=200, blank=False, verbose_name='Nombre')
    level = models.IntegerField(choices=LEVEL_CHOICES, blank=False, verbose_name='Nivel')
    description = models.TextField(verbose_name='Descripción', blank=True, null=True)
    min_price = models.IntegerField(blank=False, verbose_name='Precio Min')
    max_price = models.IntegerField(blank=False, verbose_name='Precio Max')
    increment = models.IntegerField(blank=False, verbose_name='Incremento', default=1000)
    active = models.BooleanField(default=True, verbose_name='Activo')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Subject(models.Model):
    def images_folder(self, filename):
        return '/'.join(['subject', 'images', str(self.id), re.sub('[^0-9a-zA-Z._]+', '', unidecode(filename))])

    area = models.ForeignKey(Area, related_name='area_subjects', verbose_name='Area', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name='Nombre')
    description = models.TextField(verbose_name='Descripción', blank=True, null=True)
    image = models.ImageField(verbose_name='Imagen', blank=True, null=True, upload_to=images_folder)
    active = models.BooleanField(default=True, verbose_name='Activo')
    visible = models.BooleanField(default=False, verbose_name='Visible', help_text='Visible en la sección de materias')

    class Meta:
        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'
        ordering = ['name']

    def __str__(self):
        return self.name


# Clase para almacenar la informacion de los pagos a los docentes (archivos de excel generados para pagar por parte de tuto experts)
class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user', on_delete=models.SET_NULL, null=True)
    status = models.IntegerField(verbose_name='Estado', choices=PAYMENT_STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True, editable=False, verbose_name='Fecha')

    def __str__(self):
        return '%s, %s' % (str(self.pk), self.created_at.strftime('%A %d %B, %Y %I:%M %p'))

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'


class Reservation(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='student_reservations', verbose_name='Estudiante', on_delete=models.CASCADE)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='teacher_reservations', verbose_name='Docente', on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, related_name='subject_reservations', verbose_name='Materia', on_delete=models.CASCADE)
    topic = models.TextField(verbose_name='Tema')
    duration = models.IntegerField(verbose_name='Duración')
    start_datetime_class = models.DateTimeField(verbose_name='Fecha y Hora Inicio')
    end_datetime_class = models.DateTimeField(verbose_name='Fecha y Hora Fin')
    mode = models.IntegerField(choices=CLASS_MODE_CHOICES, verbose_name='Modalidad')
    price = models.FloatField(verbose_name='Valor total')
    amount_to_paid = models.FloatField(default=0)
    paid = models.BooleanField(default=False, help_text='Pagada al docente', verbose_name='Pagado a docente')
    address = models.TextField(blank=True, null=True)
    edited_at = models.DateTimeField(auto_now_add=False, auto_now=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False)
    payment = models.ForeignKey(Payment, on_delete=models.DO_NOTHING, blank=True, null=True)
    payment_proof = models.CharField(blank=True, null=True, max_length=50, verbose_name='Número de transacción', help_text='Referencia de pago (cuando se pague al docente)')
    confirmed = models.BooleanField(db_index=True, default=False, verbose_name='Confirmado por Estudiante')
    # Campos de payu
    reference_code = models.CharField(max_length=50, verbose_name='Código de referencia', blank=True, null=True)
    order_id = models.BigIntegerField(verbose_name='Orden Payu', db_index=True, help_text='Número de orden generado por Payu', default=1)
    transaction_id = models.CharField(max_length=50, verbose_name='No Transacción', db_index=True, default='')
    status = models.CharField(max_length=100, verbose_name='Estado', db_index=True, default='Pendiente')
    trazability_code = models.CharField(max_length=50, verbose_name='Código de Trazabilidad', db_index=True, default='')
    authorization_code = models.CharField(max_length=50, verbose_name='Código de Autorización', blank=True, null=True)
    url_payment_pdf = models.URLField(verbose_name='PDF', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')
    url_payment_web = models.URLField(verbose_name='WEB', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')
    reference_number = models.BigIntegerField(verbose_name='No Referencia', blank=True, null=True, help_text='Solo aplica para pagos en efectivo')

    def __str__(self):
        return self.topic

    class Meta:
        ordering = ['created_at']
        verbose_name = 'Reserva'
        verbose_name_plural = 'Reservas'

users/templates/payments/payment_response.html
{% extends "base.html" %}
<!-- archivos staticos -->
{% load i18n static humanize mathfilters %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Confirmación {% endblock title %}
<!-- Meta -->
{% block meta %}
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
{% endblock meta %}
<!-- Contenido -->
{% block content %}

<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <div class="title-block">
                <h3><span>{{user.first_name}} {{user.last_name}}</span></h3>
                <span>A continuación el detalle de su pago</span>
            </div>

            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td>Empresa</td>
                        <td>Tuto Experts</td>
                    </tr>
                    <tr>
                        <td>NIT</td>
                        <td>13456789-0</td>
                    </tr>
                    <tr>
                        <td>Fecha</td>
                        <td>{{reservation.created_at|date:"D d F \d\e Y - P"}}</td>
                    </tr>
                    <tr>
                        <td>Estado</td>
                        <td>{{reservation_status}}</td>
                    </tr>
                    <tr>
                        <td>Referencia</td>
                        <td>{{request.GET.referenceCode}}</td>
                    </tr>
                    <tr>
                        <td>Transacción</td>
                        <td>{{request.GET.transactionId|upper}}</td>
                    </tr>
                    <tr>
                        <td>Número de Transacción / CUS</td>
                        <td>{{request.GET.cus|upper}}</td>
                    </tr>
                    <tr>
                        <td>Banco</td>
                        <td>{{request.GET.pseBank|upper}}</td>
                    </tr>
                    <tr>
                        <td>Valor</td>
                        <td>${{request.GET.TX_VALUE|floatformat:'0'|intcomma}}</td>
                    </tr>
                    <tr>
                        <td>Moneda</td>
                        <td>{{request.GET.currency}}</td>
                    </tr>
                    <tr>
                        <td>Descripción</td>
                        <td>{{request.GET.description}}</td>
                    </tr>
                    <tr>
                        <td>IP Origen</td>
                        <td>{{request.GET.pseReference1}}</td>
                    </tr>
                </tbody>
            </table>
            <section>
                {% if reservation_status != 'Transacción Aprobada' %}
                <a href="{% url 'checkout' %}" class="button button-3d button-rounded button-green"><i class="fa-icon-repeat"></i>Reintentar Transacción</a>
                {% endif %}
                <a href="{% url 'users:reservation' reservation.pk %}" class="button button-3d button-rounded button-green"><i class="icon-bill"></i>Finalizar Transacción</a>
                <button id="btnPrint" class="button button-3d button-rounded button-green"><i class="fa-icon-print"></i>Imprimir</button>
            </section>
        </div>
    </div>
</section>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
    $('#btnPrint').click(function () {
        var prtContent = document.getElementById("content");
        var WinPrint = window.open('', '', 'left=0,top=0,width=800,height=900,toolbar=0,scrollbars=0,status=0');
        WinPrint.document.write(prtContent.innerHTML);
        WinPrint.document.close();
        WinPrint.focus();
        WinPrint.print();
        WinPrint.close();
    })
</script>
{% endblock extra_js %}

users/templates/payments/reservation_detail.html
{% extends "base.html" %}
<!-- archivos staticos -->
{% load i18n static humanize mathfilters widget_tweaks %}
<!-- bloque de titulo -->
{% block title %} {{ block.super }} | Detalle de Reserva {% endblock title %}
<!-- Meta -->
{% block meta %}
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
{% endblock meta %}
<!-- Contenido -->
{% block content %}

<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <h3>Detalle de la reserva</h3>


            {% if show_alert %}
            <div class="style-msg successmsg">
                <div class="sb-msg"><i class="icon-thumbs-up"></i><strong>¡Muy bien!</strong> Su reserva ha sido confirmada correctamente.</div>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            </div>
            {% endif %}


            <blockquote>
                <p>{{reservation.topic}}</p>
            </blockquote>

            <div class="line notopmargin"></div>

            <div class="col_one_fifth">
                <div class="feature-box fbox-center fbox-plain">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-user"></i></a>
                    </div>
                    <h3>{% if is_teacher %}Estudiante{% else %}docente{% endif %}</h3>
                    <p>{% if is_teacher %}{{reservation.student.get_full_name|truncatechars:30}}{% else %}{{reservation.teacher.get_full_name|truncatechars:30}}{% endif %}</p>
                </div>
            </div>

            <div class="col_one_fifth">
                <div class="feature-box fbox-center fbox-plain">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-type"></i></a>
                    </div>
                    <h3>Materia</h3>
                    <p>{{reservation.subject|truncatechars:30}}</p>
                </div>
            </div>

            <div class="col_one_fifth">
                <div class="feature-box fbox-center fbox-plain">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-clock"></i></a>
                    </div>
                    <h3>Fecha y Hora</h3>
                    <p>{{reservation.start_datetime_class|date:'D d M, Y h:i A'}}</p>
                </div>
            </div>

            <div class="col_one_fifth">
                <div class="feature-box fbox-center fbox-plain">
                    <div class="fbox-icon">
                        <a href="#"><i class="fa-icon-hourglass"></i></a>
                    </div>
                    <h3>Duración</h3>
                    <p>{{reservation.duration}}hr{{reservation.duration|pluralize}}</p>
                </div>
            </div>

            <div class="col_one_fifth col_last">
                <div class="feature-box fbox-center fbox-plain">
                    <div class="fbox-icon">
                        <a href="#"><i class="{% if reservation.mode == 1 %}icon-users{% else %}icon-laptop{% endif %}"></i></a>
                    </div>
                    <h3>Modalidad</h3>
                    <p>{{reservation.get_mode_display}}</p>
                </div>
            </div>

            {% if not is_teacher %}

            {% if reservation.status == 'Transacción aprobada' %}

            <div class="col_full fancy-title title-double-border">
                <h4>Datos del docente</h4>
            </div>

            <div class="col_one_third">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-mail"></i></a>
                    </div>
                    <h3>Correo</h3>
                    <p><a href="mailto:{{reservation.teacher.email}}">{{reservation.teacher.email}}</a></p>
                </div>
            </div>

            <div class="col_one_third">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-phone3"></i></a>
                    </div>
                    <h3>Télefono</h3>
                    <p><a href="tel:{{reservation.teacher.teacher.phone}}">{{reservation.teacher.teacher.phone|default_if_none:"--"}}</a></p>
                </div>
            </div>

            <div class="col_one_third col_last">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-skype"></i></a>
                    </div>
                    <h3>Skype</h3>
                    <p><a href="skype:{{reservation.teacher.teacher.skype_user}}">{{reservation.teacher.teacher.skype_user|default_if_none:"--"}}</a></p>
                </div>
            </div>

            {% endif %}


            {% if payu_information %}

            <h3>Datos de facturación</h3>

            <div class="line notopmargin"></div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-clipboard"></i></a>
                    </div>
                    <h3>Método</h3>
                    <p>{{payu_information.paymentMethod}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="{% if reservation.status == 'Transacción aprobada' %}icon-check{% elif reservation.status == 'Pendiente' %}icon-line2-hourglass{% else %}icon-ban-circle{% endif %}"></i></a>
                    </div>
                    <h3>Estado</h3>
                    <p>{{reservation.status}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-money"></i></a>
                    </div>
                    <h3>Valor</h3>
                    <p>${{reservation.price|floatformat:'0'|intcomma}}</p>
                </div>
            </div>

            <div class="col_one_fourth col_last">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-bill"></i></a>
                    </div>
                    <h3>Referencia</h3>
                    <p style="overflow-wrap: break-word;">{{reservation.reference_code}}</p>
                </div>
            </div>

            <div class="col_full fancy-title title-double-border">
                <h4>Datos del comprador</h4>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-user2"></i></a>
                    </div>
                    <h3>Nombre</h3>
                    <p>{{payu_information.buyer.fullName}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-mail"></i></a>
                    </div>
                    <h3>Correo</h3>
                    <p>{{payu_information.buyer.emailAddress}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-line2-home"></i></a>
                    </div>
                    <h3>Dirección</h3>
                    <p>{{payu_information.buyer.buyerAddress.street1}} - {{payu_information.buyer.buyerAddress.city}}</p>
                </div>
            </div>

            <div class="col_one_fourth col_last">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-phone3"></i></a>
                    </div>
                    <h3>Teléfono</h3>
                    <p>{{payu_information.buyer.contactPhone}}</p>
                </div>
            </div>

            {% if payu_information.paymentMethod != 'BALOTO' and payu_information.paymentMethod != 'EFECTY' %}

            <div class="col_full fancy-title title-double-border">
                <h4>Datos del pagador</h4>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-user"></i></a>
                    </div>
                    <h3>Nombre</h3>
                    <p>{{payu_information.payer.fullName}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-email3"></i></a>
                    </div>
                    <h3>Correo</h3>
                    <p>{{payu_information.payer.emailAddress}}</p>
                </div>
            </div>

            <div class="col_one_fourth">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="icon-phone3"></i></a>
                    </div>
                    <h3>Teléfono</h3>
                    <p>{{payu_information.payer.contactPhone}}</p>
                </div>
            </div>

            <div class="col_one_fourth col_last">
                <div class="feature-box fbox-border fbox-dark fbox-effect">
                    <div class="fbox-icon">
                        <a href="#"><i class="fa-icon-bank"></i></a>
                    </div>
                    <h3>Banco</h3>
                    <p>{{payu_information.bankName}}</p>
                </div>
            </div>

            {% endif %}{% comment "cierro si de metodo de pago" %}{% endcomment %}

            {% endif %}{% comment "cierro si de si es profesor" %}{% endcomment %}

            {% endif %}{% comment "cierro si de payu_information" %}{% endcomment %}
        </div>
    </div>
</section>
{% endblock content %}